first_name = input('What is your first name? ')
last_name = input('What is your last name? ')
email_address = input('Please, type your email: ')
phone_number = input('Please, type your phone number: ')
job_title = input('What is your job title? ')
ID_number = input('Please, type your ID Number: ')

print('\nThe ID Card is:')
print('----------------------------------------')
print(f'{last_name.upper()}, {first_name}')
print(job_title.title())
print(f'ID: {ID_number}\n')
print(email_address.lower())
print(phone_number)
print('----------------------------------------')